// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.audit.v1;

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/audit/v1";

// Action is the set of actions that the BSR records in its audit log.
enum Action {
  ACTION_UNSPECIFIED = 0;
  ACTION_ORGANIZATION_CREATED = 1;
  ACTION_ORGANIZATION_DELETED = 2;
  ACTION_ORGANIZATION_MEMBER_ADDED = 3;
  ACTION_ORGANIZATION_MEMBER_ROLE_CHANGED = 4 [deprecated = true];
  ACTION_ORGANIZATION_MEMBER_ROLES_CHANGED = 50;
  ACTION_ORGANIZATION_MEMBER_REMOVED = 5;
  ACTION_ORGANIZATION_IDP_GROUP_ADDED = 21;
  ACTION_ORGANIZATION_IDP_GROUP_UPDATED = 59;
  ACTION_ORGANIZATION_IDP_GROUP_REMOVED = 22;
  ACTION_ORGANIZATION_RESOURCE_VISIBILITY_CONTROL_CHANGED = 81;
  ACTION_ORGANIZATION_UNIQUENESS_POLICY_ENABLED = 82;
  ACTION_ORGANIZATION_UNIQUENESS_POLICY_DISABLED = 83;
  ACTION_REPOSITORY_CREATED = 6;
  ACTION_REPOSITORY_DEPRECATED = 48;
  ACTION_REPOSITORY_UNDEPRECATED = 49;
  ACTION_REPOSITORY_DELETED = 7;
  ACTION_REPOSITORY_COMMIT_PUSHED = 8;
  ACTION_REPOSITORY_CONTRIBUTOR_ADDED = 9;
  ACTION_REPOSITORY_CONTRIBUTOR_ROLE_CHANGED = 10;
  ACTION_REPOSITORY_CONTRIBUTOR_ROLES_CHANGED = 63;
  ACTION_REPOSITORY_CONTRIBUTOR_REMOVED = 11;
  ACTION_REPOSITORY_VISIBILITY_CHANGED = 12;
  ACTION_REPOSITORY_DEFAULT_LABEL_NAME_CHANGED = 40;
  ACTION_REPOSITORY_IDP_GROUP_ADDED = 60;
  ACTION_REPOSITORY_IDP_GROUP_UPDATED = 61;
  ACTION_REPOSITORY_IDP_GROUP_REMOVED = 62;
  ACTION_POLICY_CREATED = 54;
  ACTION_POLICY_DELETED = 55;
  ACTION_POLICY_DEPRECATED = 56;
  ACTION_POLICY_UNDEPRECATED = 57;
  ACTION_POLICY_VISIBILITY_CHANGED = 58;
  ACTION_POLICY_COMMIT_PUSHED = 64;
  ACTION_POLICY_LABEL_CREATED = 65;
  ACTION_POLICY_LABEL_MOVED = 66;
  ACTION_POLICY_LABEL_ARCHIVED = 67;
  ACTION_POLICY_LABEL_UNARCHIVED = 68;
  ACTION_PLUGIN_CREATED = 13;
  ACTION_PLUGIN_DELETED = 14;
  ACTION_PLUGIN_DEPRECATED = 51;
  ACTION_PLUGIN_UNDEPRECATED = 52;
  ACTION_PLUGIN_VISIBILITY_CHANGED = 53;
  ACTION_PLUGIN_COMMIT_PUSHED = 43;
  ACTION_CURATED_PLUGIN_CREATED = 20;
  ACTION_CURATED_PLUGIN_DELETED = 31;
  ACTION_CURATED_PLUGIN_STATUS_UPDATED = 78;
  ACTION_USER_CREATED = 15;
  ACTION_USER_DELETED = 16;
  ACTION_USER_DEACTIVATED = 17;
  ACTION_USER_LOGGED_IN = 18;
  ACTION_USER_LOGGED_OUT = 19;
  ACTION_TOKEN_CREATED = 23;
  ACTION_TOKEN_DELETED = 24;
  ACTION_USER_REACTIVATED = 25;
  ACTION_SCIM_TOKEN_CREATED = 26;
  ACTION_SCIM_TOKEN_DELETED = 27;
  ACTION_REPOSITORY_COMMIT_DELETED = 28 [deprecated = true];
  ACTION_REPOSITORY_LABEL_CREATED = 29;
  ACTION_REPOSITORY_LABEL_MOVED = 30;
  ACTION_REPOSITORY_LABEL_ARCHIVED = 38;
  ACTION_REPOSITORY_LABEL_UNARCHIVED = 39;
  ACTION_REPOSITORY_LABEL_ENFORCEMENT_IGNORES_CHANGED = 79;
  ACTION_SERVER_BREAKING_CHANGE_POLICY_ENABLED = 32;
  ACTION_SERVER_BREAKING_CHANGE_POLICY_DISABLED = 33;
  ACTION_REPOSITORY_DEFAULT_BRANCH_CHANGED = 34 [deprecated = true];
  ACTION_SERVER_UNIQUENESS_POLICY_ENABLED = 35;
  ACTION_SERVER_UNIQUENESS_POLICY_DISABLED = 36;
  ACTION_SERVER_RESOURCE_VISIBILITY_CONTROL_CHANGED = 80;
  ACTION_USER_AUTO_MERGED_FROM_NEW_IDP = 37;
  ACTION_DEVICE_AUTHORIZATION_GRANT_APPROVED = 41;
  ACTION_DEVICE_AUTHORIZATION_GRANT_DENIED = 42;
  ACTION_PLUGIN_LABEL_CREATED = 44;
  ACTION_PLUGIN_LABEL_MOVED = 45;
  ACTION_PLUGIN_LABEL_ARCHIVED = 46;
  ACTION_PLUGIN_LABEL_UNARCHIVED = 47;
  ACTION_SERVER_REVIEW_FLOW_ENABLED = 69;
  ACTION_SERVER_REVIEW_FLOW_DISABLED = 70;
  ACTION_SDK_PLUGIN_CONSTRAINT_CREATED = 71;
  ACTION_SDK_PLUGIN_CONSTRAINT_UPDATED = 72;
  ACTION_SDK_PLUGIN_CONSTRAINT_DELETED = 73;
  ACTION_POLICY_ENFORCEMENT_CREATED = 74;
  ACTION_POLICY_ENFORCEMENT_DELETED = 75;
  ACTION_POLICY_ENFORCEMENT_POLICY_CHANGED = 76;
  ACTION_POLICY_ENFORCEMENT_TARGETS_CHANGED = 77;
  ACTION_AUTHORIZATION_REQUEST_APPROVED = 84;
  ACTION_AUTHORIZATION_REQUEST_DENIED = 85;
}
