// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.search.v1;

import "buf/registry/module/v1/module.proto";
import "buf/registry/owner/v1/owner.proto";
import "buf/registry/search/v1/search_enums.proto";
import "buf/validate/validate.proto";

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/search/v1";

message UserFilter {
  // searches across given_name and family_name
  string name = 1;
  string email = 2;
  VerificationStatus verification_status = 3 [(buf.validate.field).enum.defined_only = true];
  UserType user_type = 4 [(buf.validate.field).enum.defined_only = true];
  UserState user_state = 5 [(buf.validate.field).enum.defined_only = true];
  string description = 6;
}

message OrgFilter {
  VerificationStatus verification_status = 1 [(buf.validate.field).enum.defined_only = true];
  string description = 2;
}

message ModuleFilter {
  // The specific Owners to limit matched modules to.
  //
  // If empty, resources are not filtered by Owner.
  repeated buf.registry.owner.v1.OwnerRef owner_refs = 1;
  Visibility visibility = 2 [(buf.validate.field).enum.defined_only = true];
  bool deprecated = 3;
  string description = 4;
  bool buf_managed = 5;
}

message PluginFilter {
  bool deprecated = 1;
  Visibility visibility = 2 [(buf.validate.field).enum.defined_only = true];
  bool verified = 3;
  RegistryType registry_type = 4 [(buf.validate.field).enum.defined_only = true];
  // if more than one value specified, they are ORed together
  repeated OutputLanguage output_languages = 5 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.items = {enum: {defined_only: true}}
  ];
}

message ElementFilter {
  // The specific Owners to limit matched elements to.
  //
  // If empty, resources are not filtered by Owner.
  repeated buf.registry.owner.v1.OwnerRef owner_refs = 1;
  // The specific Modules to limit matched elements to.
  //
  // If empty, resources are not filtered by Module.
  repeated buf.registry.module.v1.ModuleRef module_refs = 2;
  ElementType element_type = 3 [(buf.validate.field).enum.defined_only = true];
  string package_name = 4;
}

message FileFilter {
  // The specific Owners to limit matched files to.
  //
  // If empty, resources are not filtered by Owner.
  repeated buf.registry.owner.v1.OwnerRef owner_refs = 1;
  // The specific Modules to limit matched files to.
  //
  // If empty, resources are not filtered by Module.
  repeated buf.registry.module.v1.ModuleRef module_refs = 2;
}

message TeamFilter {}
