// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.search.v1;

import "buf/registry/module/v1/module.proto";
import "buf/registry/owner/v1/owner.proto";
import "buf/registry/search/v1/search_enums.proto";
import "buf/validate/validate.proto";

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/search/v1";

message UserResult {
  string user_name = 1 [(buf.validate.field).required = true];
  string given_name = 2;
  string family_name = 3;
  string email = 4;
  VerificationStatus verification_status = 5 [(buf.validate.field).enum.defined_only = true];
  UserType user_type = 6 [(buf.validate.field).enum.defined_only = true];
  UserState user_state = 7 [(buf.validate.field).enum.defined_only = true];
  string description = 8;
  string url = 9;
}

message OrgResult {
  string name = 1 [(buf.validate.field).required = true];
  VerificationStatus verification_status = 2 [(buf.validate.field).enum.defined_only = true];
  string description = 3;
  string url = 4;
  BaseRepositoryRole base_repository_role = 5 [(buf.validate.field).enum.defined_only = true];
}

message ModuleResult {
  string name = 1 [(buf.validate.field).required = true];
  buf.registry.owner.v1.OwnerRef owner_ref = 2;
  Visibility visibility = 3 [(buf.validate.field).enum.defined_only = true];
  bool deprecated = 4;
  string description = 5;
  bool buf_managed = 6;
}

message PluginResult {
  string name = 1 [(buf.validate.field).required = true];
  bool deprecated = 2;
  Visibility visibility = 3 [(buf.validate.field).enum.defined_only = true];
  bool verified = 4;
  RegistryType registry_type = 5 [(buf.validate.field).enum.defined_only = true];
  repeated OutputLanguage output_languages = 6 [(buf.validate.field).repeated.items = {
    enum: {defined_only: true}
  }];
  string spdx_license_id = 7;
}

message ElementResult {
  string name = 1 [(buf.validate.field).required = true];
  buf.registry.owner.v1.OwnerRef owner_ref = 2;
  buf.registry.module.v1.ModuleRef module_ref = 3;
  ElementType element_type = 4 [(buf.validate.field).enum.defined_only = true];
  string package_name = 5;
}

message FileResult {
  string name = 1 [(buf.validate.field).required = true];
  buf.registry.owner.v1.OwnerRef owner_ref = 2;
  buf.registry.module.v1.ModuleRef module_ref = 3;
}

message TeamResult {
  string name = 1 [(buf.validate.field).required = true];
}
