// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.search.v1;

import "buf/registry/module/v1/module.proto";
import "buf/registry/owner/v1/owner.proto";
import "buf/registry/priv/extension/v1beta1/extension.proto";
import "buf/registry/search/v1/search_result.proto";
import "buf/validate/validate.proto";

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/search/v1";

// Search the BSR.
service SearchService {
  // Search for Owners and resources by name and metadata.
  //
  // Results only include Owners and resources that the caller is authorized to see.
  // Results are ordered by relevance, which is determined by the server and may change
  // over time.
  rpc Search(SearchRequest) returns (SearchResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.search.resource";
  }
  // Search the content of Modules for named elements of the Protobuf schema, such as
  // messages and services, and for files.
  //
  // The content searched for each Module is the content of the head Commit of the
  // Module's default Label. Results only include Modules that the caller is authorized
  // to see. Results are ordered by relevance, which is determined by the server and may
  // change over time.
  rpc SearchContent(SearchContentRequest) returns (SearchContentResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.search.content";
  }
}

enum SortOrder {
  SORT_ORDER_UNSPECIFIED = 0;
  SORT_ORDER_NAME_ASC = 1;
  SORT_ORDER_NAME_DESC = 2;
  SORT_ORDER_CREATE_DATE_ASC = 3;
  SORT_ORDER_CREATE_DATE_DESC = 4;
  SORT_ORDER_MOD_DATE_ASC = 5;
  SORT_ORDER_MOD_DATE_DESC = 6;
}

message SearchRequest {
  // The search query.
  string query = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 256
  ];
  // The maximum number of items to return.
  //
  // The default value is 10.
  uint32 page_size = 2 [(buf.validate.field).uint32.lte = 250];
  // The page to start from.
  //
  // If empty, the first page is returned.
  string page_token = 3 [(buf.validate.field).string.max_len = 4096];
  // The specific Owners to limit matched resources to.
  //
  // If empty, resources are not filtered by Owner. Owners themselves are only matched
  // when this is empty.
  repeated buf.registry.owner.v1.OwnerRef owner_refs = 5;
  // Sort order for results
  //
  // If unspecified, use SORT_ORDER_NAME_ASC
  optional SortOrder sort_order = 6 [
    (buf.validate.field).enum.defined_only = true,
    (buf.validate.field).enum.not_in = 0
  ];
}

message SearchResponse {
  // The next page token.
  //
  // If empty, there are no more pages.
  string next_page_token = 1 [(buf.validate.field).string.max_len = 4096];
  // The search results.
  repeated SearchResult search_results = 2;
}

message SearchContentRequest {
  // The kind of a match that can be returned by a content search.
  enum Kind {
    KIND_UNSPECIFIED = 0;
    // Match named elements of the Protobuf schema, such as messages and services.
    KIND_ELEMENT = 1;
    // Match files.
    KIND_FILE = 2;
  }
  // The search query.
  string query = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 256
  ];
  // The maximum number of items to return.
  //
  // The default value is 10.
  uint32 page_size = 2 [(buf.validate.field).uint32.lte = 250];
  // The page to start from.
  //
  // If empty, the first page is returned.
  string page_token = 3 [(buf.validate.field).string.max_len = 4096];
  // The kinds of matches to return.
  //
  // If empty, matches of all kinds are returned.
  repeated Kind kinds = 4 [
    // only two kinds of item, expand if we add more
    (buf.validate.field).repeated.max_items = 2,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items.enum.defined_only = true,
    (buf.validate.field).repeated.items.enum.not_in = 0
  ];
  // The specific Owners to limit the search to.
  //
  // If empty, content is not filtered by Owner.
  repeated buf.registry.owner.v1.OwnerRef owner_refs = 5;
  // The specific Modules to limit the search to.
  //
  // If empty, content is not filtered by Module.
  repeated buf.registry.module.v1.ModuleRef module_refs = 6;
  // Sort order for results
  //
  // If unspecified, use SORT_ORDER_NAME_ASC
  optional SortOrder sort_order = 7 [
    (buf.validate.field).enum.defined_only = true,
    (buf.validate.field).enum.not_in = 0
  ];
}

message SearchContentResponse {
  // The next page token.
  //
  // If empty, there are no more pages.
  string next_page_token = 1 [(buf.validate.field).string.max_len = 4096];
  // The content search results.
  repeated ContentSearchResult content_search_results = 2;
}
