// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.gensdk.v1;

import "buf/registry/gensdk/v1/gensdk.proto";
import "buf/registry/plugin/v1beta1/plugin.proto";
import "buf/registry/resource/v1/resource_visibility_control.proto";
import "buf/validate/validate.proto";

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/gensdk/v1";

// Manage which plugins automatically generate SDKs when the default label of a module is updated.
service GenSDKService {
  // Add a plugin to the list of plugins that auto-generate SDKs at a specified level.
  //
  // The plugin is also added to the Recommended SDK list.
  // Returns an error with code ALREADY_EXISTS if the plugin is already configured to auto-generate SDKs at the
  // specified level.
  rpc AddGenSDK(AddGenSDKRequest) returns (AddGenSDKResponse) {
    option idempotency_level = IDEMPOTENT;
  }
  // Remove a plugin from the list of plugins that auto-generate SDKs at a specified level.
  // The plugin is also removed from the Recommended SDK list.
  rpc RemoveGenSDK(RemoveGenSDKRequest) returns (RemoveGenSDKResponse) {
    option idempotency_level = IDEMPOTENT;
  }
  // List the plugins that auto-generate SDKs at a specified level.
  //
  // Because the same plugin can be configured to auto-generate SDKs at more than one level, callers can
  // make a request per level to determine whether a plugin is auto-generating SDKs at a higher level.
  rpc ListGenSDKs(ListGenSDKsRequest) returns (ListGenSDKsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
}

message AddGenSDKRequest {
  // The Plugin that generates the SDK.
  buf.registry.plugin.v1beta1.PluginRef plugin_ref = 1 [(buf.validate.field).required = true];
  // The level at which the plugin will auto-generate the SDK.
  SDKGenerationLevelRef generation_level = 2 [(buf.validate.field).required = true];
}

message AddGenSDKResponse {}

message RemoveGenSDKRequest {
  // The Plugin that should stop generating the SDK.
  buf.registry.plugin.v1beta1.PluginRef plugin_ref = 1 [(buf.validate.field).required = true];
  // The level at which to stop auto-generating with the specified plugin.
  SDKGenerationLevelRef generation_level = 2 [(buf.validate.field).required = true];
}

message RemoveGenSDKResponse {}

message ListGenSDKsRequest {
  // The maximum number of items to return on a page.
  //
  // The default value is 10.
  uint32 page_size = 1 [(buf.validate.field).uint32.lte = 250];
  // The page to start from.
  //
  // If empty, the first page is returned.
  string page_token = 2 [(buf.validate.field).string.max_len = 4096];
  // The level at which to list plugins that auto-generate SDKs.
  //
  // Only plugins that auto-generate at this level are included in the response.
  SDKGenerationLevelRef generation_level = 3 [(buf.validate.field).required = true];
}

message ListGenSDKsResponse {
  // The next page token.
  //
  // If empty, there are no more pages.
  string next_page_token = 1 [(buf.validate.field).string.max_len = 4096];
  // The level at which the plugins are auto-generating.
  SDKGenerationLevel generation_level = 2 [(buf.validate.field).required = true];
  // The plugins that auto-generate SDKs on default label update, at the level given on the request.
  repeated GenSDK generated_sdks = 3;
}
