// Copyright 2020-2026 Buf Technologies, Inc.
//
// All rights reserved.

syntax = "proto3";

package buf.registry.iam.v1;

import "buf/registry/iam/v1/principal.proto";
import "buf/registry/priv/extension/v1beta1/extension.proto";
import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

// Password is an Identity for a Principal authenticated via an email/password.
//
// There is at most one Password per Principal. Only User Principals can have Password Identities.
message Password {
  // The ID of the Password.
  //
  // The ID uniquely identifies the Password.
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.tuuid = true
  ];
  // The time the Password was created.
  google.protobuf.Timestamp create_time = 2 [(buf.validate.field).required = true];
  // The time the Password was last updated.
  google.protobuf.Timestamp update_time = 3 [(buf.validate.field).required = true];
  // The ID of the Principal who owns the Password.
  string principal_id = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.tuuid = true
  ];
  // The state of the Password.
  PasswordState state = 5 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
}

// PasswordRef is a reference to a Password, either by id or by owning Principal.
message PasswordRef {
  option (buf.registry.priv.extension.v1beta1.message).request_only = true;

  oneof value {
    option (buf.validate.oneof).required = true;
    // The id of the Password.
    string id = 1 [(buf.validate.field).string.tuuid = true];
    // The Principal that owns the Password.
    PrincipalRef principal_ref = 2;
  }
}

// PasswordState is the state of a Password.
enum PasswordState {
  PASSWORD_STATE_UNSPECIFIED = 0;
  // The Password is active and can be used to authenticate.
  PASSWORD_STATE_ACTIVE = 1;
  // The Password has been reset by an admin. The Principal must change their password on the next
  // login.
  PASSWORD_STATE_RESET = 2;
  // The Password has been locked after consecutive failed authentication attempts. An admin must
  // unlock the Password before it can be used to authenticate.
  PASSWORD_STATE_LOCKED = 3;
}
