// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.iam.v1;

import "buf/registry/iam/v1/validate.proto";
import "buf/registry/priv/extension/v1beta1/extension.proto";
import "buf/validate/validate.proto";

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/iam/v1";

// RoleRef is a reference to a Role, either an id or a name.
message RoleRef {
  option (buf.registry.priv.extension.v1beta1.message).request_only = true;

  message Name {
    // The ID of the Resource.
    //
    // If empty, global Roles are searched.
    string resource_id = 1 [
      (buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE,
      (buf.validate.field).string.tuuid = true
    ];
    // The name of the Role.
    string name = 2 [(buf.validate.field).string.(role_name) = true];
  }
  oneof value {
    option (buf.validate.oneof).required = true;
    // The id of the Role.
    string id = 1 [(buf.validate.field).string.tuuid = true];
    // The name of the Role.
    Name name = 2;
  }
}
