// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.iam.v1;

import "buf/registry/iam/v1/role.proto";
import "buf/registry/priv/extension/v1beta1/extension.proto";
import "buf/validate/validate.proto";

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/iam/v1";

// Operate on Roles.
service RoleService {
  // Get Roles by id or name.
  rpc GetRoles(GetRolesRequest) returns (GetRolesResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.role.get";
  }
  // List Roles.
  rpc ListRoles(ListRolesRequest) returns (ListRolesResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.role.list";
  }
}

message GetRolesRequest {
  // The references to the Roles to retrieve.
  repeated RoleRef role_refs = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 250
  ];
}

message GetRolesResponse {
  // The retrieved Roles in the same order as requested.
  repeated Role roles = 1 [(buf.validate.field).repeated.min_items = 1];
}

message ListRolesRequest {
  // The maximum number of items to return.
  //
  // The default value is 10.
  uint32 page_size = 1 [(buf.validate.field).uint32.lte = 250];
  // The page to start from.
  //
  // If empty, the first page is returned.
  string page_token = 2 [(buf.validate.field).string.max_len = 4096];
  // Only return Roles with a name that contains this string using a case-insensitive comparison.
  string name_query = 3 [(buf.validate.field).string.max_len = 255];
}

message ListRolesResponse {
  // The next page token.
  //
  // If empty, there are no more pages.
  string next_page_token = 1 [(buf.validate.field).string.max_len = 4096];
  // The listed Roles in alphabetical order by name.
  repeated Role roles = 2;
}
