// Copyright 2023-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package buf.registry.owner.v1;

import "buf/registry/owner/v1/organization.proto";
import "buf/registry/owner/v1/organization_membership.proto";
import "buf/registry/owner/v1/user.proto";
import "buf/registry/priv/extension/v1beta1/extension.proto";
import "buf/registry/priv/validate/v1beta1/validate.proto";
import "buf/validate/validate.proto";

option go_package = "buf.build/gen/go/bufbuild/registry/protocolbuffers/go/buf/registry/owner/v1";

// Operate on the membership of Users in Organizations.
//
// This service is a convenience over buf.registry.iam.v1.RoleBindingService for the common
// case of managing the members of an Organization. Memberships managed by this service are
// RoleBindings whose subject is the User and whose scope is the Organization, and changes
// made via RoleBindingService are reflected by this service.
service OrganizationMembershipService {
  // Get the memberships of Users in Organizations.
  rpc GetOrganizationMemberships(GetOrganizationMembershipsRequest) returns (GetOrganizationMembershipsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.organization.membership.get";
  }
  // List memberships, by Organization, by User, or instance-wide.
  rpc ListOrganizationMemberships(ListOrganizationMembershipsRequest) returns (ListOrganizationMembershipsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.organization.membership.list";
  }
  // Add Users as members of Organizations.
  //
  // An error is returned if the User is already a member of the Organization; use
  // UpdateOrganizationMemberships to change the Role of an existing member.
  //
  // This operation is atomic. Either all memberships are created or an error is returned.
  rpc CreateOrganizationMemberships(CreateOrganizationMembershipsRequest) returns (CreateOrganizationMembershipsResponse) {
    option idempotency_level = IDEMPOTENT;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.organization.membership.create";
  }
  // Update the Roles of members of Organizations.
  //
  // An error is returned if the operation would leave an Organization without any member
  // holding a Role that grants administration of the Organization.
  //
  // This operation is atomic. Either all memberships are updated or an error is returned.
  rpc UpdateOrganizationMemberships(UpdateOrganizationMembershipsRequest) returns (UpdateOrganizationMembershipsResponse) {
    option idempotency_level = IDEMPOTENT;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.organization.membership.update";
  }
  // Remove members from Organizations.
  //
  // An error is returned if the operation would leave an Organization without any member
  // holding a Role that grants administration of the Organization.
  //
  // This operation is atomic. Either all memberships are deleted or an error is returned.
  rpc DeleteOrganizationMemberships(DeleteOrganizationMembershipsRequest) returns (DeleteOrganizationMembershipsResponse) {
    option idempotency_level = IDEMPOTENT;
    option (buf.registry.priv.extension.v1beta1.method).required_permission = "bsr.organization.membership.delete";
  }
}

message GetOrganizationMembershipsRequest {
  // The memberships to request.
  repeated OrganizationMembershipRef organization_membership_refs = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 250
  ];
}

message GetOrganizationMembershipsResponse {
  // The retrieved memberships in the same order as requested.
  repeated OrganizationMembership organization_memberships = 1 [(buf.validate.field).repeated.min_items = 1];
}

message ListOrganizationMembershipsRequest {
  // The list order.
  enum Order {
    ORDER_UNSPECIFIED = 0;
    // Order by create_time newest to oldest.
    ORDER_CREATE_TIME_DESC = 1;
    // Order by create_time oldest to newest.
    ORDER_CREATE_TIME_ASC = 2;
  }
  // The maximum number of items to return.
  //
  // The default value is 10.
  uint32 page_size = 1 [(buf.validate.field).uint32.lte = 250];
  // The page to start from.
  //
  // If empty, the first page is returned.
  string page_token = 2 [(buf.validate.field).string.max_len = 4096];
  // The specific Organizations to list memberships for.
  //
  // If empty, memberships are not filtered by Organization.
  repeated OrganizationRef organization_refs = 3;
  // The specific Users to list memberships for.
  //
  // If empty, memberships are not filtered by User.
  //
  // If both organization_refs and user_refs are empty, all memberships on the instance are
  // listed, but this functionality is limited to Users with the necessary permissions.
  repeated UserRef user_refs = 4;
  // The order to return the memberships.
  //
  // If not specified, defaults to ORDER_CREATE_TIME_DESC.
  Order order = 5 [(buf.validate.field).enum.defined_only = true];
}

message ListOrganizationMembershipsResponse {
  // The next page token.
  //
  // If empty, there are no more pages.
  string next_page_token = 1 [(buf.validate.field).string.max_len = 4096];
  // The listed memberships.
  repeated OrganizationMembership organization_memberships = 2;
}

message CreateOrganizationMembershipsRequest {
  // An individual request to add a User as a member of an Organization.
  message Value {
    // The Organization to add the User to.
    OrganizationRef organization_ref = 1 [(buf.validate.field).required = true];
    // The User to add as a member.
    UserRef user_ref = 2 [(buf.validate.field).required = true];
    // The name of the Role that the User will hold on the Organization.
    //
    // The Role must exist and must grant Permissions applicable to Organizations,
    // otherwise an error is returned.
    string role_name = 3 [
      (buf.validate.field).required = true,
      (buf.validate.field).string.(buf.registry.priv.validate.v1beta1.role_name) = true
    ];
  }
  // The memberships to create.
  repeated Value values = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 250
  ];
}

message CreateOrganizationMembershipsResponse {
  // The created memberships in the same order as given on the request.
  repeated OrganizationMembership organization_memberships = 1 [(buf.validate.field).repeated.min_items = 1];
}

message UpdateOrganizationMembershipsRequest {
  // An individual request to update the Role of a member of an Organization.
  message Value {
    // The membership to update.
    OrganizationMembershipRef organization_membership_ref = 1 [(buf.validate.field).required = true];
    // The name of the Role that the User will hold on the Organization, replacing the
    // Role the User currently holds.
    //
    // The Role must exist and must grant Permissions applicable to Organizations,
    // otherwise an error is returned.
    string role_name = 2 [
      (buf.validate.field).required = true,
      (buf.validate.field).string.(buf.registry.priv.validate.v1beta1.role_name) = true
    ];
  }
  // The memberships to update.
  repeated Value values = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 250
  ];
}

message UpdateOrganizationMembershipsResponse {
  // The updated memberships in the same order as given on the request.
  repeated OrganizationMembership organization_memberships = 1 [(buf.validate.field).repeated.min_items = 1];
}

message DeleteOrganizationMembershipsRequest {
  // The memberships to delete.
  repeated OrganizationMembershipRef organization_membership_refs = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 250
  ];
}

message DeleteOrganizationMembershipsResponse {}
