name: ci
on: push
permissions: read-all
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache-dependency-path: Makefile
      - name: make
        run: make
      - name: make checkgenerate
        run: make checkgenerate
