name: ci
on: push
permissions: read-all
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          # Must be able to run the latest version of `buf`, which updates
          # every once in a while.
          go-version: 'stable'
          # No caching needed; no Go files.
          cache: false
      - run: make
      - run: make checkgenerate
