name: ci
on: push
permissions: read-all
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false
      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-registry-proto-ci-${{ hashFiles('.bufversion') }}
          restore-keys: ${{ runner.os }}-registry-proto-ci-
      - name: make
        run: make
      - name: make checkgenerate
        run: make checkgenerate
