name: ci
on: push
permissions: read-all
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          # Check for latest Go version to run latest Buf version.
          check-latest: true
          # No caching needed; no Go files.
          cache: false
      - run: make
      - run: make checkgenerate
